- hosts: localhost
  become: true
  vars:
    source_key: "./.ssh/github_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/github_rsa"
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    # - include: tasks/dotfiles.yml

