- name: Install nodejs and npm
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - nodejs
- name: Install fnm
  shell: curl -fsSL https://fnm.vercel.app/install | bash
  tags:
    - install
    - node
- name: Add fnm to PATH
  shell: source ~/.zshrc
  tags:
    - install
    - node
- name: Download and install node.js
  shell: fnm use --install-if-missing 20
  tags:
    - install
    - node