- name: Install nodejs and npm
  apt:
    name: ["nodejs", "npm"]
  tags:
    - install
    - nodejs
- name: Install Volta
  ansible.builtin.shell: curl https://get.volta.sh | bash
  tags:
    - install
    - node
- name: Install the latest LTS version
  ansible.builtin.shell: volta install node
  tags:
    - install
    - node
